# (END POINTS)

#(BOOKS ROUTES)

###
GET http://localhost:3001/books?limit=(NUMBER)&page=(NUMBER) HTTP/1.1

###
GET http://localhost:3001/books?name=(NAME)&discount=(asc/desc)&price=(asc/desc)&released=(asc/desc)&sort=(asc/desc)&genre=(GENRE)&status=(false/true)&limit=(NUMBER)&page=(1...) HTTP/1.1

###
GET http://localhost:3001/books/:idBook HTTP/1.1

###
POST http://localhost:3001/books/ HTTP/1.1
Content-Type: application/json

{
    "name":"book test",
    "image":"image test",
    "description":"description test",
    "price": 0,
    "used": false,
    "released":"00-00-00"
}

###
PUT http://localhost:3001/books/62d95f66dbd810b17e2d3026 HTTP/1.1
Content-Type: application/json

{
    "price": 37
}

###
PUT http://localhost:3001/books/:idBook/:idUser HTTP/1.1

###
DELETE http://localhost:3001/books/  HTTP/1.1


####################################################

#(USERS ROUTES)

###
GET http://localhost:3001/users/ HTTP/1.1

###
GET http://localhost:3001/users/:idUser HTTP/1.1

###
PUT http://localhost:3001/users/:idUser HTTP/1.1
Content-Type: application/json

{
    "name":"name updated"
}

###
POST http://localhost:3001/users/register HTTP/1.1
Content-Type: application/json

{
    "name":"juan",
    "email":"juan@email.com",
    "password":"password"
}

###
PUT http://localhost:3001/users/:idUser/:idBook HTTP/1.1


###
DELETE http://localhost:3001/users/:idUser HTTP/1.1