# (END POINTS)

#(BOOKS ROUTES)

###
GET http://localhost:3000/books/ HTTP/1.1

###
GET http://localhost:3000/books/:idBook HTTP/1.1

###
POST http://localhost:3000/books/ HTTP/1.1
Content-Type: application/json

{
    "name":"book test",
    "image":"image test",
    "description":"description test",
    "price": 0,
    "used": false,
    "released":"00-00-00"
}

###
PUT http://localhost:3000/books/:idBook HTTP/1.1
Content-Type: application/json

{
    "description":"description test fixed"
}

###
PUT http://localhost:3000/books/:idBook/:idUser HTTP/1.1

###
DELETE http://localhost:3000/books/:idBook  HTTP/1.1


####################################################

#(USERS ROUTES)

###
GET http://localhost:3000/users/ 
    Content-Type: application/json
    RETORNA TODOS LOS USUARIOS 

###
GET http://localhost:3000/users/:idUser
    Content-Type: application/json
    RETORNA EL USUARIO

##
PUT http://localhost:3000/users/:idUser 
    Content-Type: application/json
    RETORNA MENSAJE DE ACTUALIZACION
    {status: 'Usuario actualizado.'}

##
POST http://localhost:3000/users/register
    Content-Type: application/json
    RETORNA MENSAJE DE CREACION
    { status: 'usuario registrado y guardado en la base de datos.' }


##
PUT http://localhost:3000/users/:idUser/:idBook 
    Content-Type: application/json
    RETORNA EL USUARIO CON LOS LIBROS AGREGADOS

##
DELETE http://localhost:3000/users/:idUser
       Content-Type: application/json
       { status: 'Usuario eliminado' }

