# (END POINTS)

#(BOOKS ROUTES)

###
GET http://localhost:3000/books/ HTTP/1.1

###
GET http://localhost:3000/books/:idBook HTTP/1.1

###
POST http://localhost:3000/books/ HTTP/1.1
Content-Type: application/json

{
    "name":"book test",
    "image":"image test",
    "description":"description test",
    "price": 0,
    "used": false,
    "released":"00-00-00"
}

###
PUT http://localhost:3000/books/:idBook HTTP/1.1
Content-Type: application/json

{
    "description":"description test fixed"
}

###
PUT http://localhost:3000/books/:idBook/:idUser HTTP/1.1

###
DELETE http://localhost:3000/books/:idBook  HTTP/1.1


####################################################

#(BOOKS ROUTES)

###
GET http://localhost:3000/users/ HTTP/1.1


// USER: 62d79b20507e3f9e6a53b05e
// BOOK: 62d71ff86fc15b86cd177cf3
